name: Build PX4 SITL AppImage

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  actions: write

jobs:
  build-appimage:
    name: "AppImage ${{ matrix.arch }}"
    strategy:
      fail-fast: false
      matrix:
        - arch: amd64
          runs-on: ubuntu-22.04
        - arch: arm64
          runs-on: ubuntu-22.04-arm64
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Install Dependencies
        run: ./Tools/setup/ubuntu.sh

      - name: Build PX4 SITL and AppImage
        env:
          # avoid FUSE by extracting the AppImage in‐place
          APPIMAGE_EXTRACT_AND_RUN: "1"
        run: |
          make appimage

      - name: Upload AppImage artifact
        uses: actions/upload-artifact@v4
        with:
          name: px4-sitl-appimage-${{ matrix.arch }}
          path: build/*.AppImage
