name: Build PX4 SITL AppImage

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  actions: write

jobs:
  build-appimage:
    name: "Create px4_sitl AppImage"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Install Dependencies
        run: ./Tools/setup.sh

      - name: Build PX4 SITL and AppImage
        env:
          # avoid FUSE by extracting the AppImage in‐place
          APPIMAGE_EXTRACT_AND_RUN: "1"
        run: |
          make appimage

      - name: Upload AppImage artifact
        uses: actions/upload-artifact@v4
        with:
          name: px4-sitl-appimage
          path: build/*.AppImage
